name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release_default:
    uses: bactions/workflows/.github/workflows/release-go-lib.yml@main
    with:
      version: ${{ github.ref_name }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
